import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const FIXTURE = fileURLToPath(new URL("../../fixtures/jb2a-db.json", import.meta.url));

/** Fresh copy of the trimmed JB2A database fixture (generated by tools/extract_db_fixture.py). */
export function loadFixture() {
  return JSON.parse(readFileSync(FIXTURE, "utf8"));
}

/** Deterministic `random` that cycles through the given values. */
export function sequence(...values) {
  let i = 0;
  return () => values[i++ % values.length];
}
